export const ITEMS_REQUEST = 'ITEMS_REQUEST';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAILURE = 'ITEMS_FAILURE';

export const REFERENCES_REQUEST = 'REFERENCES_REQUEST';
export const REFERENCES_SUCCESS = 'REFERENCES_SUCCESS';
export const REFERENCES_FAILURE = 'REFERENCES_FAILURE';

export const ITEM_REQUEST = 'ITEM_REQUEST';
export const ITEM_EDIT = 'ITEM_EDIT';
export const ITEM_FAILURE = 'ITEM_FAILURE';

export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';
export const LOGOUT = 'LOGOUT';

export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
